export const FETCH_BLOG_BEGIN = "FETCH_BLOG_BEGIN"
export const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS"
export const FETCH_BLOG_FAILED = "FETCH_BLOG_FAILED"
export const FETCH_SINGLE_BLOG_BEGIN = "FETCH_SINGLE_BLOG_BEGIN"
export const FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS"
export const FETCH_SINGLE_BLOG_FAILED = "FETCH_SINGLE_BLOG_FAILED"
export const FETCH_SEARCH_BLOG_BEGIN = "FETCH_SEARCH_BLOG_BEGIN"
export const FETCH_SEARCH_BLOG_SUCCESS = "FETCH_SEARCH_BLOG_SUCCESS"
export const FETCH_SEARCH_BLOG_FAILED = "FETCH_SEARCH_BLOG_FAILED"
export const SET_SEARCH_TERM = "SET_SEARCH_TERM"
export const FETCH_SINGLE_USER_BEGIN = "FETCH_SINGLE_USER_BEGIN"
export const FETCH_SINGLE_USER_SUCCESS = "FETCH_SINGLE_USER_SUCCESS"
export const FETCH_SINGLE_USER_FAILED = "FETCH_SINGLE_USER_FAILED"
export const FETCH_COMMENTS_BEGIN = "FETCH_COMMENTS_BEGIN"
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS"
export const FETCH_COMMENTS_FAILED = "FETCH_COMMENTS_FAILED"




export const BLOG_URL = "posts"
export const USER_URL = "users"
export const COMMENT_BY_POSR_URL = "comments/post"
export const SEARCH_URL = "posts/search?q="